// Taxonomía v2 del gold set (2026-07-31) — mantener en sincronía con
// pjn-api/src/controllers/etapaAnotacionesController.js (DIMENSIONES).

export const DIMENSIONES_ORDEN = [
	"tipoResolucion",
	"instancia",
	"materia",
	"contexto",
	"funcion",
	"resultado",
] as const;
export type DimKey = (typeof DIMENSIONES_ORDEN)[number] | "modoTerminacion" | "estadoImpugnatorio";

export const DIM_LABELS: Record<DimKey, { titulo: string; corto: string; opciones: [string, string][] }> = {
	tipoResolucion: {
		titulo: "Tipo de resolución",
		corto: "Tipo",
		opciones: [
			["providencia_simple", "Providencia simple"],
			["sentencia_interlocutoria", "Sent. interlocutoria"],
			["sentencia_definitiva", "Sent. definitiva"],
			["otra_resolucion", "Otra resolución"],
			["no_es_resolucion", "No es resolución"],
		],
	},
	instancia: {
		titulo: "Instancia (del órgano emisor)",
		corto: "Instancia",
		opciones: [
			["primera_instancia", "Primera"],
			["segunda_instancia", "Segunda"],
			["superior_tribunal_provincial", "Sup. Trib. provincial"],
			["csjn", "CSJN"],
			["instancia_unica", "Única"],
			["otro", "Otro"],
			["indeterminada", "Indeterminada"],
		],
	},
	materia: {
		titulo: "Materia decisoria",
		corto: "Materia",
		opciones: [
			["fondo", "Fondo"],
			["prueba", "Prueba"],
			["competencia", "Competencia"],
			["cautelar", "Cautelar"],
			["honorarios", "Honorarios"],
			["costas", "Costas"],
			["liquidacion", "Liquidación"],
			["ejecucion", "Ejecución"],
			["recurso", "Recurso"],
			["nulidad", "Nulidad"],
			["otro", "Otro"],
		],
	},
	contexto: {
		titulo: "Contexto procesal",
		corto: "Contexto",
		opciones: [
			["principal", "Principal"],
			["incidental", "Incidental"],
			["ejecucion", "Ejecución"],
			["recursiva", "Recursiva"],
			["cautelar", "Cautelar"],
			["otro", "Otro"],
		],
	},
	funcion: {
		titulo: "Función / efecto",
		corto: "Función",
		opciones: [
			["impulso", "Impulso"],
			["ordenacion", "Ordenación"],
			["decision", "Decisión"],
			["terminacion", "Terminación"],
			["suspension", "Suspensión"],
			["reanudacion", "Reanudación"],
			["otro", "Otro"],
		],
	},
	modoTerminacion: {
		titulo: "Modo de terminación",
		corto: "Modo term.",
		opciones: [
			["sentencia_sobre_fondo", "Sentencia sobre fondo"],
			["allanamiento", "Allanamiento"],
			["desistimiento_del_proceso", "Desist. del proceso"],
			["desistimiento_del_derecho", "Desist. del derecho"],
			["transaccion", "Transacción"],
			["conciliacion", "Conciliación"],
			["caducidad_de_instancia", "Caducidad de instancia"],
			["homologacion_de_acuerdo", "Homologación"],
			["sustraccion_de_materia", "Sustracción de materia"],
			["declaracion_de_abstraccion", "Abstracción"],
			["archivo", "Archivo"],
			["incompetencia_con_remision", "Incompetencia c/remisión"],
			["otro", "Otro"],
		],
	},
	estadoImpugnatorio: {
		titulo: "Estado impugnatorio",
		corto: "Firmeza",
		opciones: [
			["recurrible", "Recurrible"],
			["recurrida", "Recurrida"],
			["firme", "Firme"],
			["no_determinado", "No determinado"],
		],
	},
	resultado: {
		titulo: "Resultado (decisión principal)",
		corto: "Resultado",
		opciones: [
			["hace_lugar", "Hace lugar"],
			["hace_lugar_parcialmente", "Hace lugar parcialmente"],
			["rechaza", "Rechaza"],
			["confirma", "Confirma"],
			["revoca", "Revoca"],
			["modifica", "Modifica"],
			["desierto", "Desierto"],
			["concede", "Concede"],
			["deniega", "Deniega"],
			["homologa", "Homologa"],
			["no_aplica", "No aplica"],
			["otro", "Otro"],
		],
	},
};

export const ACTOS_PROCESALES: [string, string][] = [
	["corre_traslado", "Corre traslado"],
	["intima", "Intima"],
	["fija_audiencia", "Fija audiencia"],
	["ordena_notificacion", "Ordena notificación"],
	["ordena_oficio", "Ordena oficio"],
	["ordena_cedula", "Ordena cédula"],
	["tiene_presente", "Tiene presente"],
	["agrega_documentacion", "Agrega documentación"],
	["abre_a_prueba", "Abre a prueba"],
	["declara_causa_puro_derecho", "Declara puro derecho"],
	["pasa_autos_sentencia", "Pasa autos a sentencia"],
	["regula_honorarios", "Regula honorarios"],
	["aprueba_liquidacion", "Aprueba liquidación"],
	["declara_rebeldia", "Declara rebeldía"],
	["declara_caducidad", "Declara caducidad"],
	["concede_recurso", "Concede recurso"],
	["deniega_recurso", "Deniega recurso"],
	["resuelve_fondo", "Resuelve el fondo"],
	["homologa_acuerdo", "Homologa acuerdo"],
	["ordena_embargo", "Ordena embargo"],
	["levanta_embargo", "Levanta embargo"],
	["suspende_proceso", "Suspende el proceso"],
	["reanuda_proceso", "Reanuda el proceso"],
	["archiva", "Archiva"],
	["otro", "Otro"],
];

export const DESTINATARIOS: [string, string][] = [
	["actora", "Actora"],
	["demandada", "Demandada"],
	["ambas_partes", "Ambas partes"],
	["perito", "Perito"],
	["testigo", "Testigo"],
	["tercero", "Tercero"],
	["organismo_publico", "Organismo público"],
	["letrado", "Letrado"],
	["sindico", "Síndico"],
	["banco_o_registro", "Banco/Registro"],
	["oficial_de_justicia", "Oficial de justicia"],
	["otro", "Otro"],
];

// Acto-primero: elegir el acto autocompleta (solo campos vacíos) las demás
// dimensiones con la combinación típica. El anotador confirma o corrige.
export const ACTO_AUTOFILL: Record<
	string,
	Partial<Record<"tipoResolucion" | "materia" | "contexto" | "funcion" | "resultado" | "modoTerminacion", string>>
> = {
	corre_traslado: { tipoResolucion: "providencia_simple", funcion: "impulso", resultado: "no_aplica" },
	intima: { tipoResolucion: "providencia_simple", funcion: "ordenacion", resultado: "no_aplica" },
	fija_audiencia: { tipoResolucion: "providencia_simple", funcion: "ordenacion", resultado: "no_aplica" },
	ordena_notificacion: { tipoResolucion: "providencia_simple", funcion: "ordenacion", resultado: "no_aplica" },
	ordena_oficio: { tipoResolucion: "providencia_simple", funcion: "ordenacion", resultado: "no_aplica" },
	ordena_cedula: { tipoResolucion: "providencia_simple", funcion: "ordenacion", resultado: "no_aplica" },
	tiene_presente: { tipoResolucion: "providencia_simple", funcion: "impulso", resultado: "no_aplica" },
	agrega_documentacion: { tipoResolucion: "providencia_simple", funcion: "impulso", resultado: "no_aplica" },
	abre_a_prueba: { tipoResolucion: "providencia_simple", materia: "prueba", funcion: "ordenacion", resultado: "no_aplica" },
	declara_causa_puro_derecho: { tipoResolucion: "sentencia_interlocutoria", materia: "prueba", funcion: "decision" },
	pasa_autos_sentencia: { tipoResolucion: "providencia_simple", funcion: "impulso", resultado: "no_aplica" },
	regula_honorarios: { materia: "honorarios", funcion: "decision" },
	aprueba_liquidacion: { materia: "liquidacion", contexto: "ejecucion", funcion: "decision", resultado: "hace_lugar" },
	declara_rebeldia: { tipoResolucion: "sentencia_interlocutoria", funcion: "decision" },
	declara_caducidad: { tipoResolucion: "sentencia_interlocutoria", funcion: "terminacion", modoTerminacion: "caducidad_de_instancia" },
	concede_recurso: { tipoResolucion: "providencia_simple", materia: "recurso", funcion: "impulso", resultado: "concede" },
	deniega_recurso: { materia: "recurso", funcion: "decision", resultado: "deniega" },
	resuelve_fondo: { tipoResolucion: "sentencia_definitiva", materia: "fondo", funcion: "decision" },
	homologa_acuerdo: { funcion: "terminacion", modoTerminacion: "homologacion_de_acuerdo", resultado: "homologa" },
	ordena_embargo: { tipoResolucion: "sentencia_interlocutoria", materia: "cautelar", funcion: "decision", resultado: "hace_lugar" },
	levanta_embargo: { tipoResolucion: "sentencia_interlocutoria", materia: "cautelar", funcion: "decision" },
	suspende_proceso: { funcion: "suspension" },
	reanuda_proceso: { funcion: "reanudacion" },
	archiva: { tipoResolucion: "providencia_simple", funcion: "terminacion", modoTerminacion: "archivo", resultado: "no_aplica" },
};

export const DIM_CHIP_COLOR: Record<string, "primary" | "secondary" | "info" | "warning" | "success" | "error" | "default"> = {
	tipoResolucion: "primary",
	instancia: "secondary",
	materia: "warning",
	contexto: "info",
	funcion: "success",
	modoTerminacion: "error",
	estadoImpugnatorio: "default",
	actoProcesal: "primary",
	resultado: "success",
};
