// assets
import {
	Setting3,
	Folder2,
	MoneyRecive,
	Status,
	Sms,
	Receipt1,
	ProfileCircle,
	Notification,
	DocumentText,
	Wallet2,
	MessageQuestion,
	TaskSquare,
	Box1,
	People,
	Judge,
} from "iconsax-react";

// type
import { NavItemType } from "types/menu";

// ==============================|| ADMIN MENU ITEMS ||============================== //

const admin: NavItemType = {
	id: "admin",
	title: "Administración",
	type: "group",
	children: [
		{
			id: "workers",
			title: "Workers",
			type: "collapse",
			icon: Setting3,
			breadcrumbs: true,
			children: [
				{
					id: "workers-pjn",
					title: "Workers PJN",
					type: "item",
					url: "/admin/causas/workers",
					breadcrumbs: true,
				},
				{
					id: "workers-mev",
					title: "Workers MEV",
					type: "item",
					url: "/admin/workers/mev",
					breadcrumbs: true,
				},
				{
					id: "workers-eje",
					title: "Workers EJE",
					type: "item",
					url: "/admin/eje/workers",
					breadcrumbs: true,
				},
				{
					id: "workers-logs",
					title: "Logs",
					type: "item",
					url: "/admin/workers/logs",
					breadcrumbs: true,
				},
				{
					id: "workers-email-verification",
					title: "Worker de Emails",
					type: "item",
					url: "/admin/workers/email-verification",
					breadcrumbs: true,
				},
				{
					id: "workers-rag",
					title: "Workers RAG",
					type: "item",
					url: "/admin/workers/rag",
					breadcrumbs: true,
					chip: { label: "6", color: "primary", variant: "outlined", size: "small" },
				},
				{
					id: "workers-corpus",
					title: "Workers Corpus (IA)",
					type: "item",
					url: "/admin/workers/corpus",
					breadcrumbs: true,
					chip: { label: "1", color: "default", variant: "outlined", size: "small" },
				},
				{
					id: "workers-escritos",
					title: "Worker Escritos (IA)",
					type: "item",
					url: "/admin/workers/escritos",
					breadcrumbs: true,
					chip: { label: "2", color: "warning", variant: "outlined", size: "small" },
				},
				{
					id: "workers-sentencias",
					title: "Worker Sentencias (IA)",
					type: "item",
					url: "/admin/workers/sentencias",
					breadcrumbs: true,
					chip: { label: "6", color: "warning", variant: "outlined", size: "small" },
				},
				{
					id: "workers-movimientos",
					title: "Worker Update (IA)",
					type: "item",
					url: "/admin/workers/movimientos",
					breadcrumbs: true,
					chip: { label: "mgr", color: "default", variant: "outlined", size: "small" },
				},
				{
					id: "infrastructure",
					title: "Infraestructura",
					type: "item",
					url: "/admin/infrastructure",
					breadcrumbs: true,
				},
				{
					id: "workers-saij",
					title: "Workers SAIJ",
					type: "item",
					url: "/admin/workers/saij",
					breadcrumbs: true,
				},
				{
					id: "workers-seclo",
					title: "Workers SECLO",
					type: "item",
					url: "/admin/workers/seclo",
					breadcrumbs: true,
				},
				{
					id: "workers-scraper-postal",
					title: "Scraper Postal",
					type: "item",
					url: "/admin/workers/scraper",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "causas-pending",
			title: "Causas Pendientes de Verificación",
			type: "item",
			icon: Folder2,
			url: "/admin/causas/pending",
			breadcrumbs: true,
		},
		{
			id: "causas",
			title: "Carpetas PJN",
			type: "collapse",
			icon: Folder2,
			breadcrumbs: true,
			children: [
				{
					id: "causas-credentials",
					title: "Credenciales PJN",
					type: "item",
					url: "/admin/causas/credentials",
					breadcrumbs: true,
				},
				{
					id: "causas-verified-worker",
					title: "Carpetas Verificadas (Worker)",
					type: "item",
					url: "/admin/causas/verified",
					breadcrumbs: true,
				},
				{
					id: "causas-verified-app",
					title: "Carpetas Verificadas (App)",
					type: "item",
					url: "/admin/causas/verified-app",
					breadcrumbs: true,
				},
				{
					id: "causas-non-verified",
					title: "Carpetas No Verificadas (App)",
					type: "item",
					url: "/admin/causas/non-verified",
					breadcrumbs: true,
				},
				{
					id: "causas-synced-credentials",
					title: "Causas por Credencial",
					type: "item",
					url: "/admin/causas/synced-credentials",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "carpetas-mev",
			title: "Carpetas MEV",
			type: "collapse",
			icon: Folder2,
			breadcrumbs: true,
			children: [
				{
					id: "mev-scba-credentials",
					title: "Credenciales SCBA",
					type: "item",
					url: "/admin/mev/scba-credentials",
					breadcrumbs: true,
				},
				{
					id: "mev-verified-app",
					title: "Carpetas Verificadas (App)",
					type: "item",
					url: "/admin/mev/verified-app",
					breadcrumbs: true,
				},
				{
					id: "mev-non-verified",
					title: "Carpetas No Verificadas (App)",
					type: "item",
					url: "/admin/mev/non-verified",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "carpetas-eje",
			title: "Carpetas EJE",
			type: "collapse",
			icon: Folder2,
			breadcrumbs: true,
			children: [
				{
					id: "eje-verified-app",
					title: "Carpetas Verificadas (App)",
					type: "item",
					url: "/admin/eje/verified-app",
					breadcrumbs: true,
				},
				{
					id: "eje-non-verified",
					title: "Carpetas No Verificadas (App)",
					type: "item",
					url: "/admin/eje/non-verified",
					breadcrumbs: true,
				},
				{
					id: "eje-pivots",
					title: "Pivots (Múltiples Resultados)",
					type: "item",
					url: "/admin/eje/pivots",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "app-folders",
			title: "Carpetas (App)",
			type: "item",
			icon: Folder2,
			url: "/admin/folders",
			breadcrumbs: true,
		},
		{
			id: "postal-tracking",
			title: "Seguimientos Postales",
			type: "item",
			icon: Box1,
			url: "/admin/postal-tracking",
			breadcrumbs: true,
		},
		{
			id: "escritos",
			title: "Escritos judiciales",
			type: "collapse",
			icon: DocumentText,
			breadcrumbs: true,
			children: [
				{
					id: "pdf-templates",
					title: "Modelos PDF",
					type: "item",
					url: "/admin/pdf-templates",
					breadcrumbs: true,
				},
				{
					id: "postal-documents-resources",
					title: "Escritos de usuarios",
					type: "item",
					url: "/admin/users/resources",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "groups",
			title: "Grupos de Usuarios",
			type: "item",
			icon: People,
			url: "/admin/groups",
			breadcrumbs: true,
		},
		{
			id: "subscriptions",
			title: "Suscripciones",
			type: "collapse",
			icon: MoneyRecive,
			breadcrumbs: true,
			children: [
				{
					id: "usuarios-suscripciones",
					title: "Suscripciones de Usuarios",
					type: "item",
					url: "/admin/usuarios/suscripciones",
					breadcrumbs: true,
				},
				{
					id: "stripe-webhooks",
					title: "Stripe Webhooks",
					type: "item",
					url: "/admin/subscriptions/stripe-webhooks",
					breadcrumbs: true,
				},
				{
					id: "cron-config",
					title: "Configuración de Cron",
					type: "item",
					url: "/admin/subscriptions/cron-config",
					breadcrumbs: true,
				},
				{
					id: "subscriptions-trials",
					title: "Períodos de Prueba",
					type: "item",
					url: "/admin/subscriptions/trials",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "marketing",
			title: "Marketing",
			type: "collapse",
			icon: Sms,
			breadcrumbs: true,
			children: [
				{
					id: "mailing",
					title: "Campañas de Email",
					type: "item",
					url: "/admin/marketing/mailing",
					breadcrumbs: true,
				},
				{
					id: "templates",
					title: "Plantillas de Email",
					type: "item",
					url: "/admin/marketing/templates",
					breadcrumbs: true,
				},
				{
					id: "modules",
					title: "Módulos de Email",
					type: "item",
					url: "/admin/marketing/modules",
					breadcrumbs: true,
				},
				{
					id: "contacts",
					title: "Contactos y Segmentos",
					type: "item",
					url: "/admin/marketing/contacts",
					breadcrumbs: true,
				},
				{
					id: "suppression",
					title: "Bounces y Rebotes",
					type: "item",
					url: "/admin/marketing/suppression",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "plans",
			title: "Planes",
			type: "collapse",
			icon: Receipt1,
			breadcrumbs: true,
			children: [
				{
					id: "plans-config",
					title: "Configuración de Planes",
					type: "item",
					url: "/admin/plans",
					breadcrumbs: true,
				},
				{
					id: "plans-promotions",
					title: "Promociones",
					type: "item",
					url: "/admin/plans/promotions",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "users",
			title: "Usuarios",
			type: "collapse",
			icon: ProfileCircle,
			breadcrumbs: true,
			children: [
				{
					id: "users-management",
					title: "Administracion de Usuarios",
					type: "item",
					url: "/admin/users",
					breadcrumbs: true,
				},
				{
					id: "users-config",
					title: "Configuracion",
					type: "item",
					url: "/admin/users/config",
					breadcrumbs: true,
				},
				{
					id: "users-email-logs",
					title: "Logs de Correos",
					type: "item",
					url: "/admin/users/email-logs",
					breadcrumbs: true,
				},
				{
					id: "users-onboarding",
					title: "Onboarding",
					type: "item",
					url: "/admin/users/onboarding",
					breadcrumbs: true,
				},
				{
					id: "users-resources",
					title: "Recursos",
					type: "item",
					url: "/admin/users/resources",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "notifications",
			title: "Notificaciones",
			type: "collapse",
			icon: Notification,
			breadcrumbs: true,
			children: [
				{
					id: "notifications-monitoring",
					title: "Monitoreo",
					type: "item",
					url: "/admin/notifications",
					breadcrumbs: true,
				},
				{
					id: "notifications-judicial",
					title: "Movimientos Judiciales",
					type: "item",
					url: "/admin/notifications/judicial-movements",
					breadcrumbs: true,
				},
				{
					id: "notifications-folder-inactivity",
					title: "Caducidades y Prescripciones",
					type: "item",
					url: "/admin/notifications/folder-inactivity",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "expenses",
			title: "Gastos",
			type: "item",
			icon: Wallet2,
			url: "/admin/expenses",
			breadcrumbs: true,
		},
		{
			id: "support",
			title: "Soporte",
			type: "item",
			icon: MessageQuestion,
			url: "/admin/support",
			breadcrumbs: true,
		},
		{
			id: "server-status",
			title: "Estado del Servidor",
			type: "item",
			icon: Status,
			url: "/admin/server-status",
			breadcrumbs: true,
		},
		{
			id: "admin-tasks",
			title: "Tareas",
			type: "item",
			icon: TaskSquare,
			url: "/admin/tasks",
			breadcrumbs: true,
		},
		{
			id: "seclo",
			title: "SECLO",
			type: "item",
			icon: Judge,
			url: "/admin/seclo",
			breadcrumbs: true,
		},
	],
};

export default admin;
