// assets
// Los mismos logos que la vista de integraciones y la landing usan para cada
// organismo — que un submenú de credenciales muestre el escudo del portal al
// que pertenecen ahorra leer.
import { JURISDICTION_LOGOS } from "assets/images/logos/jurisdictions";
import {
	Activity,
	ArrowSwapHorizontal,
	Book,
	Book1,
	Bookmark2,
	Box1,
	Buildings2,
	Calculator,
	Category2,
	Chart,
	Clock,
	CloseCircle,
	Cpu,
	Data2,
	DocumentText,
	Folder2,
	Health,
	Hierarchy,
	Hierarchy2,
	Judge,
	Key,
	Like1,
	Link21,
	MessageNotif,
	MessageQuestion,
	MoneyRecive,
	Note1,
	Notification,
	People,
	ProfileCircle,
	Rank,
	Receipt1,
	RefreshCircle,
	Routing2,
	Setting3,
	Sms,
	Status,
	Tag,
	TaskSquare,
	TickCircle,
	Timer1,
	Wallet2,
} from "iconsax-react";

// type
import { NavItemType } from "types/menu";

// ==============================|| ADMIN MENU ITEMS ||============================== //

const admin: NavItemType = {
	id: "admin",
	title: "Administración",
	type: "group",
	children: [
		{
			id: "causas-group",
			title: "Causas",
			type: "collapse",
			icon: Folder2,
			breadcrumbs: true,
			children: [
				{
					// Las tres vistas que cruzan jurisdicciones, juntas y separadas de los
					// grupos por jurisdicción que siguen abajo. Antes colgaban sueltas del
					// grupo "Causas", al mismo nivel que "Carpetas PJN", "Carpetas MEV" y
					// compañía, lo que las hacía parecer una jurisdicción más.
					id: "causas-todas",
					title: "Todas las jurisdicciones",
					type: "collapse",
					icon: Category2,
					breadcrumbs: true,
					children: [
						{
							id: "causas-pending",
							title: "Pendientes de verificación",
							type: "item",
							icon: Clock,
							// Ámbar, igual que "Pivotes": una cola esperando resolución.
							iconColor: "warning.main",
							url: "/admin/causas/pending",
							breadcrumbs: true,
						},
						{
							id: "app-folders",
							title: "Todas las carpetas",
							type: "item",
							icon: Folder2,
							url: "/admin/folders",
							breadcrumbs: true,
						},
						{
							id: "causas-user-view-guide",
							title: "Vista del usuario",
							type: "item",
							icon: ProfileCircle,
							url: "/admin/causas/user-view-guide",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "causas",
					title: "Carpetas PJN",
					type: "collapse",
					icon: Folder2,
					breadcrumbs: true,
					children: [
						{
							id: "causas-verified-worker",
							title: "Verificadas · worker",
							type: "item",
							icon: TickCircle,
							iconColor: "success.main",
							url: "/admin/causas/verified",
							breadcrumbs: true,
						},
						{
							id: "causas-verified-app",
							title: "Verificadas · app",
							type: "item",
							icon: TickCircle,
							iconColor: "success.main",
							url: "/admin/causas/verified-app",
							breadcrumbs: true,
						},
						{
							id: "causas-non-verified",
							title: "No verificadas",
							type: "item",
							icon: CloseCircle,
							iconColor: "error.main",
							url: "/admin/causas/non-verified",
							breadcrumbs: true,
						},
						{
							id: "causas-flujos",
							title: "Flujos de vida",
							type: "item",
							icon: Routing2,
							url: "/admin/causas/flujos",
							breadcrumbs: true,
						},
						{
							id: "causas-synced-credentials",
							title: "Por credencial",
							type: "item",
							icon: Key,
							iconColor: "info.main",
							url: "/admin/causas/synced-credentials",
							breadcrumbs: true,
						},
						{
							id: "causas-update-eligible",
							title: "En update",
							type: "item",
							icon: RefreshCircle,
							url: "/admin/causas/update-eligible",
							breadcrumbs: true,
						},
						{
							id: "causas-trayectorias",
							title: "Trayectorias",
							type: "item",
							icon: Activity,
							url: "/admin/causas/trayectorias",
							breadcrumbs: true,
						},
						{
							id: "causas-etapas",
							title: "Etapas procesales",
							type: "item",
							icon: Rank,
							url: "/admin/causas/etapas",
							breadcrumbs: true,
						},
						{
							id: "causas-etapa-stats",
							title: "Etapas · estadísticas",
							type: "item",
							icon: Chart,
							url: "/admin/causas/etapa-stats",
							breadcrumbs: true,
						},
						{
							id: "causas-etapa-arbol",
							title: "Etapas · árbol",
							type: "item",
							icon: Hierarchy2,
							url: "/admin/causas/etapa-arbol",
							breadcrumbs: true,
						},
						{
							id: "causas-etiquetado",
							title: "Etiquetado",
							type: "item",
							icon: Tag,
							url: "/admin/causas/etiquetado",
							breadcrumbs: true,
						},
						{
							id: "causas-plazos",
							title: "Plazos",
							type: "item",
							icon: Timer1,
							url: "/admin/causas/plazos",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "carpetas-mev",
					title: "Carpetas MEV",
					type: "collapse",
					icon: Folder2,
					breadcrumbs: true,
					children: [
						{
							id: "mev-verified-app",
							title: "Verificadas",
							type: "item",
							icon: TickCircle,
							iconColor: "success.main",
							url: "/admin/mev/verified-app",
							breadcrumbs: true,
						},
						{
							id: "mev-non-verified",
							title: "No verificadas",
							type: "item",
							icon: CloseCircle,
							iconColor: "error.main",
							url: "/admin/mev/non-verified",
							breadcrumbs: true,
						},
						{
							id: "mev-causes-by-credential",
							title: "Por credencial",
							type: "item",
							icon: Key,
							iconColor: "info.main",
							url: "/admin/mev/causes-by-credential",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "carpetas-eje",
					title: "Carpetas EJE",
					type: "collapse",
					icon: Folder2,
					breadcrumbs: true,
					children: [
						{
							id: "eje-verified-app",
							title: "Verificadas",
							type: "item",
							icon: TickCircle,
							iconColor: "success.main",
							url: "/admin/eje/verified-app",
							breadcrumbs: true,
						},
						{
							id: "eje-non-verified",
							title: "No verificadas",
							type: "item",
							icon: CloseCircle,
							iconColor: "error.main",
							url: "/admin/eje/non-verified",
							breadcrumbs: true,
						},
						{
							id: "eje-pivots",
							// Un pivote es una búsqueda que devolvió varias causas y quedó sin
							// resolver: Hierarchy dibuja justamente esa bifurcación.
							title: "Pivotes",
							type: "item",
							icon: Hierarchy,
							iconColor: "warning.main",
							url: "/admin/eje/pivots",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "carpetas-pjsalta",
					title: "Carpetas PJ Salta",
					type: "collapse",
					icon: Folder2,
					breadcrumbs: true,
					children: [
						{
							id: "pjsalta-verified-app",
							title: "Verificadas",
							type: "item",
							icon: TickCircle,
							iconColor: "success.main",
							url: "/admin/pjsalta/verified-app",
							breadcrumbs: true,
						},
						{
							id: "pjsalta-non-verified",
							title: "No verificadas",
							type: "item",
							icon: CloseCircle,
							iconColor: "error.main",
							url: "/admin/pjsalta/non-verified",
							breadcrumbs: true,
						},
						{
							id: "pjsalta-pivots",
							title: "Pivotes",
							type: "item",
							icon: Hierarchy,
							iconColor: "warning.main",
							url: "/admin/pjsalta/pivots",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "carpetas-pjcatamarca",
					title: "Carpetas PJ Catamarca",
					type: "collapse",
					icon: Folder2,
					breadcrumbs: true,
					children: [
						{
							id: "pjcatamarca-verified-app",
							title: "Verificadas",
							type: "item",
							icon: TickCircle,
							iconColor: "success.main",
							url: "/admin/pjcatamarca/verified-app",
							breadcrumbs: true,
						},
						{
							id: "pjcatamarca-non-verified",
							title: "No verificadas",
							type: "item",
							icon: CloseCircle,
							iconColor: "error.main",
							url: "/admin/pjcatamarca/non-verified",
							breadcrumbs: true,
						},
						{
							id: "pjcatamarca-pivots",
							title: "Pivotes",
							type: "item",
							icon: Hierarchy,
							iconColor: "warning.main",
							url: "/admin/pjcatamarca/pivots",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "carpetas-pjmendoza",
					title: "Carpetas PJ Mendoza",
					type: "collapse",
					icon: Folder2,
					breadcrumbs: true,
					children: [
						{
							id: "pjmendoza-verified-app",
							title: "Verificadas",
							type: "item",
							icon: TickCircle,
							iconColor: "success.main",
							url: "/admin/pjmendoza/verified-app",
							breadcrumbs: true,
						},
						{
							id: "pjmendoza-non-verified",
							title: "No verificadas",
							type: "item",
							icon: CloseCircle,
							iconColor: "error.main",
							url: "/admin/pjmendoza/non-verified",
							breadcrumbs: true,
						},
						{
							id: "pjmendoza-pivots",
							title: "Pivotes",
							type: "item",
							icon: Hierarchy,
							iconColor: "warning.main",
							url: "/admin/pjmendoza/pivots",
							breadcrumbs: true,
						},
					],
				},
			],
		},
		{
			id: "credenciales-group",
			title: "Credenciales",
			type: "collapse",
			icon: Key,
			breadcrumbs: true,
			children: [
				{
					id: "causas-credentials",
					title: "PJN",
					type: "item",
					iconImage: JURISDICTION_LOGOS.pjn,
					url: "/admin/causas/credentials",
					breadcrumbs: true,
				},
				{
					id: "mev-scba-credentials",
					title: "SCBA",
					type: "item",
					iconImage: JURISDICTION_LOGOS.scba,
					url: "/admin/mev/scba-credentials",
					breadcrumbs: true,
				},
				{
					id: "workers-mev-login-failures",
					title: "MEV",
					type: "item",
					iconImage: JURISDICTION_LOGOS.mev,
					url: "/admin/workers/mev-login-failures",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "workers",
			title: "Workers",
			type: "collapse",
			icon: Setting3,
			breadcrumbs: true,
			children: [
				{
					// Los siete portales judiciales que scrapeamos. Llevan el escudo del organismo,
					// el mismo que usan Carpetas y Credenciales: así se ve de un vistazo que las
					// tres entradas hablan del mismo portal.
					id: "workers-jurisdicciones",
					title: "Por jurisdicción",
					type: "collapse",
					icon: Buildings2,
					breadcrumbs: true,
					children: [
						{
							id: "workers-pjn",
							title: "PJN",
							type: "item",
							iconImage: JURISDICTION_LOGOS.pjn,
							url: "/admin/causas/workers",
							breadcrumbs: true,
						},
						{
							id: "workers-mev",
							title: "MEV",
							type: "item",
							iconImage: JURISDICTION_LOGOS.mev,
							url: "/admin/workers/mev",
							breadcrumbs: true,
						},
						{
							id: "workers-eje",
							title: "EJE",
							type: "item",
							iconImage: JURISDICTION_LOGOS.eje,
							url: "/admin/eje/workers",
							breadcrumbs: true,
						},
						{
							id: "workers-pjsalta",
							title: "PJ Salta",
							type: "item",
							iconImage: JURISDICTION_LOGOS.pjsalta,
							url: "/admin/pjsalta/workers",
							breadcrumbs: true,
						},
						{
							id: "workers-pjcatamarca",
							title: "PJ Catamarca",
							type: "item",
							iconImage: JURISDICTION_LOGOS.pjcatamarca,
							url: "/admin/pjcatamarca/workers",
							breadcrumbs: true,
						},
						{
							id: "workers-pjmendoza",
							title: "PJ Mendoza",
							type: "item",
							iconImage: JURISDICTION_LOGOS.pjmendoza,
							url: "/admin/pjmendoza/workers",
							breadcrumbs: true,
						},
						{
							id: "workers-seclo",
							title: "SECLO",
							type: "item",
							iconImage: JURISDICTION_LOGOS.seclo,
							url: "/admin/workers/seclo",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "workers-ia",
					title: "IA",
					type: "collapse",
					icon: Cpu,
					breadcrumbs: true,
					children: [
						{
							id: "workers-rag",
							title: "RAG",
							type: "item",
							icon: MessageQuestion,
							url: "/admin/workers/rag",
							breadcrumbs: true,
						},
						{
							id: "workers-corpus",
							title: "Corpus",
							type: "item",
							icon: Book1,
							url: "/admin/workers/corpus",
							breadcrumbs: true,
						},
						{
							id: "workers-escritos",
							title: "Escritos",
							type: "item",
							icon: DocumentText,
							url: "/admin/workers/escritos",
							breadcrumbs: true,
						},
						{
							id: "workers-sentencias",
							title: "Sentencias",
							type: "item",
							icon: Judge,
							url: "/admin/workers/sentencias",
							breadcrumbs: true,
						},
						{
							id: "workers-movimientos",
							title: "Update de movimientos",
							type: "item",
							icon: RefreshCircle,
							url: "/admin/workers/movimientos",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "workers-fuentes",
					title: "Fuentes normativas",
					type: "collapse",
					icon: Book,
					breadcrumbs: true,
					children: [
						{
							id: "workers-saij",
							title: "SAIJ",
							type: "collapse",
							icon: Book1,
							breadcrumbs: true,
							children: [
								{
									id: "workers-saij-estado",
									title: "Estado",
									type: "item",
									icon: Status,
									url: "/admin/workers/saij",
									breadcrumbs: true,
								},
								{
									id: "saij-conciliacion",
									title: "Conciliación",
									type: "item",
									icon: ArrowSwapHorizontal,
									url: "/admin/workers/saij?tab=conciliacion",
									breadcrumbs: true,
								},
							],
						},
						{
							id: "workers-infoleg",
							title: "InfoLeg",
							type: "item",
							icon: Receipt1,
							url: "/admin/workers/infoleg",
							breadcrumbs: true,
						},
						{
							id: "workers-cijur",
							title: "CIJur",
							type: "item",
							icon: Bookmark2,
							url: "/admin/workers/cijur",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "workers-datos",
					title: "Cálculo y datos",
					type: "collapse",
					icon: Calculator,
					breadcrumbs: true,
					children: [
						{
							id: "workers-plazos",
							title: "Plazos",
							type: "item",
							icon: Timer1,
							url: "/admin/workers/plazos",
							breadcrumbs: true,
						},
						{
							id: "workers-plazos-dataset",
							title: "Dataset de plazos",
							type: "item",
							icon: Data2,
							url: "/admin/workers/plazos-dataset",
							breadcrumbs: true,
						},
						{
							id: "workers-liquidacion",
							title: "Liquidación",
							type: "item",
							icon: MoneyRecive,
							url: "/admin/workers/liquidacion",
							breadcrumbs: true,
						},
						{
							id: "workers-scraper-postal",
							title: "Scraper postal",
							type: "item",
							icon: Box1,
							url: "/admin/workers/scraper",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "workers-soporte",
					title: "Soporte",
					type: "collapse",
					icon: Health,
					breadcrumbs: true,
					children: [
						{
							id: "workers-logs",
							title: "Logs",
							type: "item",
							icon: Note1,
							url: "/admin/workers/logs",
							breadcrumbs: true,
						},
						{
							id: "workers-email-verification",
							title: "Emails",
							type: "item",
							icon: Sms,
							url: "/admin/workers/email-verification",
							breadcrumbs: true,
						},
					],
				},
			],
		},
		{
			id: "infraestructura-group",
			title: "Infraestructura",
			type: "collapse",
			icon: Status,
			breadcrumbs: true,
			children: [
				{
					id: "server-status",
					title: "Estado del Servidor",
					type: "item",
					icon: Status,
					url: "/admin/server-status",
					breadcrumbs: true,
				},
				{
					id: "infrastructure",
					title: "Infraestructura",
					type: "item",
					url: "/admin/infrastructure",
					breadcrumbs: true,
				},
				{
					id: "data-monitoring",
					title: "Bases de datos",
					type: "item",
					url: "/admin/infrastructure/databases",
					breadcrumbs: true,
					chip: { label: "vectores", color: "primary", variant: "outlined", size: "small" },
				},
				{
					id: "portales-status",
					title: "Estado de Portales",
					type: "item",
					url: "/admin/infrastructure/portales",
					breadcrumbs: true,
					chip: { label: "PJN·SCBA·MEV", color: "success", variant: "outlined", size: "small" },
				},
				{
					id: "flujos-ecosistema",
					title: "Flujos del ecosistema",
					type: "item",
					url: "/admin/flujos",
					breadcrumbs: true,
					chip: { label: "docs", color: "primary", variant: "outlined", size: "small" },
				},
				{
					id: "data-flow",
					title: "Flujo de datos",
					type: "item",
					url: "/admin/infrastructure/dataflow",
					breadcrumbs: true,
					chip: { label: "rs0·qdrant", color: "info", variant: "outlined", size: "small" },
				},
				{
					id: "system-logs",
					title: "Logs del Ecosistema",
					type: "item",
					url: "/admin/logs",
					breadcrumbs: true,
					chip: { label: "AI", color: "secondary", variant: "outlined", size: "small" },
				},
				{
					id: "service-health",
					title: "Estado de Servicios",
					type: "item",
					url: "/admin/logs/health",
					breadcrumbs: true,
					chip: { label: "AI", color: "secondary", variant: "outlined", size: "small" },
				},
				{
					id: "integrations",
					title: "Integraciones",
					type: "collapse",
					icon: Routing2,
					breadcrumbs: true,
					children: [
						{
							id: "integrations-overview",
							title: "Resumen",
							type: "item",
							url: "/admin/integrations",
							breadcrumbs: true,
						},
						{
							id: "integrations-movement-link-analytics",
							title: "Visor de documentos",
							type: "item",
							url: "/admin/integrations/movement-link-analytics",
							breadcrumbs: true,
						},
					],
				},
			],
		},
		{
			id: "features",
			title: "Features",
			type: "collapse",
			icon: Category2,
			breadcrumbs: true,
			children: [
				{
					id: "postal-tracking",
					title: "Seguimientos Postales",
					type: "item",
					icon: Box1,
					url: "/admin/postal-tracking",
					breadcrumbs: true,
				},
				{
					id: "escritos",
					title: "Escritos judiciales",
					type: "collapse",
					icon: DocumentText,
					breadcrumbs: true,
					children: [
						{
							id: "pdf-templates",
							title: "Modelos PDF",
							type: "item",
							url: "/admin/pdf-templates",
							breadcrumbs: true,
						},
						{
							id: "postal-documents-resources",
							title: "Escritos de usuarios",
							type: "item",
							url: "/admin/users/resources?tab=escritos",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "admin-tasks",
					title: "Tareas",
					type: "item",
					icon: TaskSquare,
					url: "/admin/tasks",
					breadcrumbs: true,
				},
				{
					id: "groups",
					title: "Grupos de Usuarios",
					type: "item",
					icon: People,
					url: "/admin/groups",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "users",
			title: "Usuarios",
			type: "collapse",
			icon: ProfileCircle,
			breadcrumbs: true,
			children: [
				{
					id: "users-dashboard",
					title: "Dashboard",
					type: "item",
					url: "/admin/users/dashboard",
					breadcrumbs: true,
				},
				{
					id: "users-management",
					title: "Administracion de Usuarios",
					type: "item",
					url: "/admin/users",
					breadcrumbs: true,
				},
				{
					id: "users-config",
					title: "Configuracion",
					type: "item",
					url: "/admin/users/config",
					breadcrumbs: true,
				},
				{
					id: "users-email-logs",
					title: "Logs de Correos",
					type: "item",
					url: "/admin/users/email-logs",
					breadcrumbs: true,
				},
				{
					id: "users-onboarding",
					title: "Onboarding",
					type: "item",
					url: "/admin/users/onboarding",
					breadcrumbs: true,
				},
				{
					id: "users-resources",
					title: "Recursos",
					type: "item",
					url: "/admin/users/resources",
					breadcrumbs: true,
				},
				{
					id: "users-feature-grants",
					title: "Feature Grants (MCP)",
					type: "item",
					url: "/admin/users/feature-grants",
					breadcrumbs: true,
				},
				{
					id: "support",
					title: "Soporte",
					type: "item",
					icon: MessageQuestion,
					url: "/admin/support",
					breadcrumbs: true,
				},
				{
					id: "feedback-group",
					title: "Feedback y Encuestas",
					type: "collapse",
					icon: MessageNotif,
					breadcrumbs: true,
					children: [
						{
							id: "feedback",
							title: "Feedback recibido",
							type: "item",
							icon: Like1,
							url: "/admin/feedback",
							breadcrumbs: true,
						},
						{
							id: "surveys",
							title: "Encuestas",
							type: "item",
							icon: Chart,
							url: "/admin/surveys",
							breadcrumbs: true,
						},
						{
							id: "feedback-invites",
							title: "Invites públicos",
							type: "item",
							icon: Link21,
							url: "/admin/feedback-invites",
							breadcrumbs: true,
						},
					],
				},
			],
		},
		{
			id: "negocio-group",
			title: "Negocio",
			type: "collapse",
			icon: Wallet2,
			breadcrumbs: true,
			children: [
				{
					id: "subscriptions",
					title: "Suscripciones",
					type: "collapse",
					icon: MoneyRecive,
					breadcrumbs: true,
					children: [
						{
							id: "usuarios-suscripciones",
							title: "Suscripciones de Usuarios",
							type: "item",
							url: "/admin/usuarios/suscripciones",
							breadcrumbs: true,
						},
						{
							id: "payment-failures",
							title: "Intentos de Pago Fallidos",
							type: "item",
							url: "/admin/usuarios/payment-failures",
							breadcrumbs: true,
						},
						{
							id: "stripe-webhooks",
							title: "Stripe Webhooks",
							type: "item",
							url: "/admin/subscriptions/stripe-webhooks",
							breadcrumbs: true,
						},
						{
							id: "cron-config",
							title: "Configuración de Cron",
							type: "item",
							url: "/admin/subscriptions/cron-config",
							breadcrumbs: true,
						},
						{
							id: "subscriptions-trials",
							title: "Períodos de Prueba",
							type: "item",
							url: "/admin/subscriptions/trials",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "plans",
					title: "Planes",
					type: "collapse",
					icon: Receipt1,
					breadcrumbs: true,
					children: [
						{
							id: "plans-config",
							title: "Configuración de Planes",
							type: "item",
							url: "/admin/plans",
							breadcrumbs: true,
						},
						{
							id: "plans-promotions",
							title: "Promociones",
							type: "item",
							url: "/admin/plans/promotions",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "expenses",
					title: "Gastos",
					type: "item",
					icon: Wallet2,
					url: "/admin/expenses",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "marketing",
			title: "Marketing",
			type: "collapse",
			icon: Sms,
			breadcrumbs: true,
			children: [
				{
					id: "composer",
					title: "Compositor de Emails",
					type: "item",
					url: "/admin/marketing/composer",
					breadcrumbs: true,
				},
				{
					id: "mailing",
					title: "Campañas de Email",
					type: "item",
					url: "/admin/marketing/mailing",
					breadcrumbs: true,
				},
				{
					id: "templates",
					title: "Plantillas de Email",
					type: "item",
					url: "/admin/marketing/templates",
					breadcrumbs: true,
				},
				{
					id: "modules",
					title: "Módulos de Email",
					type: "item",
					url: "/admin/marketing/modules",
					breadcrumbs: true,
				},
				{
					id: "contacts",
					title: "Contactos y Segmentos",
					type: "item",
					url: "/admin/marketing/contacts",
					breadcrumbs: true,
				},
				{
					id: "suppression",
					title: "Bounces y Rebotes",
					type: "item",
					url: "/admin/marketing/suppression",
					breadcrumbs: true,
				},
				{
					id: "social-studio",
					title: "Posts Sociales",
					type: "item",
					url: "/admin/social/studio",
					breadcrumbs: true,
					chip: { label: "Nuevo", color: "primary", variant: "outlined", size: "small" },
				},
				{
					id: "educativo-articulos",
					title: "Artículos del Blog",
					type: "item",
					url: "/admin/social/articulos",
					breadcrumbs: true,
				},
				{
					id: "bio-links",
					title: "Link-in-bio",
					type: "item",
					url: "/admin/social/links",
					breadcrumbs: true,
				},
				{
					id: "public-banners",
					title: "Banners públicos",
					type: "item",
					url: "/admin/social/banners",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "notifications",
			title: "Notificaciones",
			type: "collapse",
			icon: Notification,
			breadcrumbs: true,
			children: [
				{
					id: "notifications-monitoring",
					title: "Monitoreo",
					type: "item",
					url: "/admin/notifications",
					breadcrumbs: true,
				},
				{
					id: "notifications-embudos",
					title: "Embudos de correo",
					type: "item",
					url: "/admin/notifications/embudos",
					breadcrumbs: true,
					chip: { label: "por fuente", color: "primary", variant: "outlined", size: "small" },
				},
				{
					id: "notifications-config",
					title: "Configuración",
					type: "item",
					url: "/admin/notifications?tab=general",
					breadcrumbs: true,
				},
				{
					id: "notifications-diagnostico",
					title: "Diagnóstico",
					type: "item",
					url: "/admin/notifications?tab=diagnostico",
					breadcrumbs: true,
				},
			],
		},
		{
			id: "contenido-group",
			title: "Contenido",
			type: "collapse",
			icon: Judge,
			breadcrumbs: true,
			children: [
				{
					id: "normas",
					title: "Normas",
					type: "collapse",
					icon: DocumentText,
					breadcrumbs: true,
					children: [
						{
							id: "normas-infoleg",
							title: "InfoLeg",
							type: "item",
							url: "/admin/normas/infoleg",
							breadcrumbs: true,
						},
					],
				},
				{
					id: "seclo",
					title: "SECLO",
					type: "item",
					icon: Judge,
					url: "/admin/seclo",
					breadcrumbs: true,
				},
			],
		},
	],
};

export default admin;
