import { FlowSpec } from "./flowTypes";

// ============================================================================
// 1. MAPA GENERAL — actores y los dos mundos de scraping
// ============================================================================
export const generalSpec: FlowSpec = {
	id: "general",
	title: "Mapa general",
	intro:
		"Los dos mundos que escriben sobre las mismas colecciones: pjn-workers (consulta pública + captcha) y pjn-mis-causas (login con credencial del usuario, sin captcha). La causa es un documento único compartido — ahí nacen los escenarios duales.",
	width: 1120,
	height: 470,
	nodes: [
		{ id: "user", x: 40, y: 30, w: 190, h: 60, kind: "actor", label: "Usuario", sub: ["law-analytics-front"] },
		{
			id: "server",
			x: 40,
			y: 160,
			w: 190,
			h: 72,
			kind: "hub",
			label: "law-analytics-server",
			sub: ["alta de folders", "vinculación de causas"],
		},
		{
			id: "uiFolder",
			x: 40,
			y: 330,
			w: 190,
			h: 84,
			kind: "ui",
			label: "UI del usuario",
			sub: ["detalle del folder", "verificationGate", "(details.tsx)"],
		},
		{ id: "cache", x: 300, y: 30, w: 170, h: 60, kind: "ext", label: "Caché PJN", sub: ["datos pre-scrapeados"] },
		{
			id: "atlas",
			x: 300,
			y: 150,
			w: 210,
			h: 96,
			kind: "db",
			label: "Atlas · causas-*",
			sub: ["doc ÚNICO por fuero+número/año", "folderIds[] · linkedCredentials[]", "verified · isValid · isPrivate"],
		},
		{
			id: "folders",
			x: 300,
			y: 330,
			w: 210,
			h: 84,
			kind: "db",
			label: "Atlas · folders",
			sub: ["causaVerified · causaIsValid", "causaAssociationStatus", "causaIsPrivate"],
		},
		{
			id: "pub",
			x: 620,
			y: 30,
			w: 230,
			h: 96,
			kind: "public",
			label: "pjn-workers · PÚBLICO",
			sub: ["verify / app-update / stuck", "privacy-checker", "consulta pública + captcha"],
		},
		{
			id: "priv",
			x: 620,
			y: 250,
			w: 230,
			h: 96,
			kind: "private",
			label: "pjn-mis-causas · PRIVADO",
			sub: ["credentials-processor", "private-causas-update-worker", "login con credencial, sin captcha"],
		},
		{ id: "pjnPub", x: 920, y: 42, w: 170, h: 72, kind: "ext", label: "PJN público", sub: ["consulta de causas", "requiere captcha"] },
		{
			id: "pjnPriv",
			x: 920,
			y: 262,
			w: 170,
			h: 72,
			kind: "ext",
			label: "Portal Mis Causas",
			sub: ["autenticado (SSO)", "ve causas reservadas"],
		},
	],
	edges: [
		{ id: "e1", from: "user", to: "server", label: "alta / búsqueda" },
		{ id: "e2", from: "server", to: "cache", label: "consulta caché" },
		{ id: "e3", from: "server", to: "atlas", label: "crea o reutiliza" },
		{ id: "e4", from: "server", to: "folders", label: "crea folder", fromSide: "bottom", toSide: "left" },
		{ id: "e5", from: "pub", to: "pjnPub", label: "scraping" },
		{ id: "e6", from: "pub", to: "atlas", label: "verifica / actualiza / flip isValid", labelDy: -6 },
		{ id: "e7", from: "priv", to: "pjnPriv", label: "login" },
		{ id: "e8", from: "priv", to: "atlas", label: "sync + updates de privadas", labelDy: 12 },
		{ id: "e9", from: "priv", to: "cache", label: "consulta al crear", fromSide: "top", toSide: "right" },
		{ id: "e10", from: "atlas", to: "folders", label: "workers propagan flags" },
		{ id: "e11", from: "folders", to: "uiFolder", kind: "problem", label: "gate: bloquea si failed / inválida" },
	],
	steps: [
		{
			title: "Vista completa",
			text: "Todos los actores. Las colecciones causas-* viven en MongoDB Atlas (cluster compartido) y son escritas por ambos mundos de scraping además del server.",
		},
		{
			title: "Dos mundos de scraping",
			text: "El público (pjn-workers, en worker_01) usa la consulta pública con captcha: no ve causas reservadas. El privado (pjn-mis-causas, en worker_02) se loguea con la credencial CUIL/password del usuario: ve todo lo del abogado, incluso causas privadas. Regla de reparto: si la causa tiene hasActiveCredential:true, el público la excluye y la trabaja el privado.",
			nodes: ["pub", "priv", "pjnPub", "pjnPriv", "atlas"],
			edges: ["e5", "e6", "e7", "e8"],
		},
		{
			title: "La causa es un doc compartido",
			text: "Cada causa existe UNA sola vez (fuero + número/año). folderIds[] permite que muchos usuarios la compartan y linkedCredentials[] que varias credenciales la sincronicen. Como ambos mundos escriben sobre el mismo documento, el orden de llegada (¿nació pública o privada?) genera los escenarios duales de la última pestaña.",
			nodes: ["atlas", "server", "pub", "priv"],
			edges: ["e3", "e6", "e8"],
		},
		{
			title: "Propagación a folders y UI",
			text: "Los workers copian el estado de la causa a los folders (causaVerified, causaIsValid, causaAssociationStatus). El front tiene un verificationGate: si el folder quedó en 'failed' o verified:true + isValid:false, reemplaza el detalle completo por PendingVerificationView — el usuario no ve movimientos ni datos.",
			nodes: ["atlas", "folders", "uiFolder", "server"],
			edges: ["e4", "e10", "e11"],
		},
	],
};

// ============================================================================
// 2. ALTA DESDE LA APP
// ============================================================================
export const altaAppSpec: FlowSpec = {
	id: "alta-app",
	title: "Alta desde la app",
	intro:
		"El usuario vincula un expediente por fuero + número/año (folderController en law-analytics-server). El orden de búsqueda es: base propia → caché PJN → crear nueva. El folder se crea siempre; su estado inicial depende de cómo se resolvió la causa.",
	width: 1120,
	height: 480,
	nodes: [
		{ id: "user", x: 40, y: 40, w: 200, h: 60, kind: "actor", label: "Usuario vincula expediente", sub: ["fuero + número/año"] },
		{ id: "server", x: 40, y: 180, w: 200, h: 60, kind: "hub", label: "law-analytics-server", sub: ["folderController"] },
		{ id: "inDb", x: 330, y: 40, w: 200, h: 60, kind: "db", label: "¿Existe en causas-*?", sub: ["Atlas, doc único"] },
		{
			id: "reuse",
			x: 640,
			y: 28,
			w: 240,
			h: 84,
			kind: "ok",
			label: "Reutiliza el doc",
			sub: ["push folderId al array", "hereda estados actuales", "(verified / isValid / isPrivate)"],
		},
		{ id: "inCache", x: 330, y: 180, w: 200, h: 60, kind: "ext", label: "¿Está en el caché PJN?" },
		{
			id: "imp",
			x: 640,
			y: 168,
			w: 240,
			h: 84,
			kind: "ok",
			label: "Importa copia del caché",
			sub: ["SOLO si la copia es isValid:true", "source: 'cache'", "(inválida → se ignora el caché)"],
		},
		{
			id: "create",
			x: 330,
			y: 330,
			w: 200,
			h: 96,
			kind: "warn",
			label: "Crea causa nueva",
			sub: ["source: 'app'", "verified: false", "espera verificación"],
		},
		{
			id: "verify",
			x: 640,
			y: 342,
			w: 240,
			h: 72,
			kind: "public",
			label: "verify-worker",
			sub: ["cola pública de verificación", "consulta con captcha"],
		},
		{
			id: "folder",
			x: 40,
			y: 320,
			w: 200,
			h: 116,
			kind: "db",
			label: "Folder creado",
			sub: ["pending → esperando verify", "success → causa válida", "failed → 'Causa inválida", "o no pública' (gate UI)"],
		},
	],
	edges: [
		{ id: "a1", from: "user", to: "server" },
		{ id: "a2", from: "server", to: "inDb", label: "1º busca" },
		{ id: "a3", from: "inDb", to: "reuse", kind: "ok", label: "sí" },
		{ id: "a4", from: "inDb", to: "inCache", label: "no" },
		{ id: "a5", from: "inCache", to: "imp", kind: "ok", label: "sí, copia válida" },
		{ id: "a6", from: "inCache", to: "create", label: "no / copia inválida" },
		{ id: "a7", from: "create", to: "verify", label: "encolada" },
		{ id: "a8", from: "server", to: "folder", label: "crea folder siempre" },
		{ id: "a9", from: "verify", to: "folder", label: "resultado → flags del folder", fromSide: "bottom", toSide: "bottom", labelDy: 14 },
	],
	steps: [
		{ title: "Vista completa", text: "Las tres resoluciones posibles de un alta manual, y el folder que se crea en paralelo." },
		{
			title: "Ya existe: reutilización",
			text: "El corazón del diseño de id único: si la causa ya está en causas-* (creada por otro usuario, por scraping masivo o por el mundo privado), NO se duplica — se agrega el folderId del nuevo usuario al array. El usuario hereda el estado actual de la causa: si venía del mundo privado con isValid:false, su folder puede nacer 'failed' aunque la causa tenga datos completos.",
			nodes: ["user", "server", "inDb", "reuse", "folder"],
			edges: ["a1", "a2", "a3", "a8"],
		},
		{
			title: "Está en el caché",
			text: "Si no estaba en la base pero sí en el caché PJN, se importa la copia con todos sus datos y source:'cache' — pero SOLO si la copia es isValid:true. Una copia inválida es una foto vieja (pudo ser privada al momento del scraping y haberse vuelto pública después): se ignora el caché y se sigue el camino de causa nueva, para que el verify-worker la verifique contra el estado ACTUAL del PJN.",
			nodes: ["user", "server", "inDb", "inCache", "imp", "folder"],
			edges: ["a1", "a2", "a4", "a5", "a8"],
		},
		{
			title: "No existe (o copia inválida): nace 'app'",
			text: "Se crea con source:'app' y verified:false, y entra a la cola del verify-worker público (vista admin 'Causas Pendientes'). Cubre dos casos: la causa no está en ningún lado, o el caché solo tenía una copia inválida que se descartó para re-verificar. El folder queda en causaAssociationStatus:'pending' hasta que el worker la resuelva.",
			nodes: ["user", "server", "inDb", "inCache", "create", "verify", "folder"],
			edges: ["a1", "a2", "a4", "a6", "a7", "a8"],
		},
		{
			title: "Estados del folder",
			text: "El folder refleja el resultado: 'pending' mientras espera, 'success' si la causa es válida, 'failed' si el verify público la declaró inexistente o inválida — en ese caso el folder queda con nombre 'Causa inválida o no pública' y el gate bloquea su detalle en la UI. Ojo: si la causa era privada, el verify público SIEMPRE falla — vincular la credencial es la vía de rescate.",
			nodes: ["folder", "verify", "server"],
			edges: ["a8", "a9"],
		},
	],
};

// ============================================================================
// 3. ALTA POR CREDENCIAL (sync pjn-mis-causas)
// ============================================================================
export const altaCredSpec: FlowSpec = {
	id: "alta-cred",
	title: "Alta por credencial",
	intro:
		"Cuando el usuario vincula su credencial PJN, credentials-processor lista el portal autenticado 'Mis Causas' y da de alta TODO el listado del abogado. Por cada causa hay 4 ramas según exista o no, y según el caché (causa-sync-service.js).",
	width: 1120,
	height: 560,
	nodes: [
		{ id: "user", x: 40, y: 40, w: 210, h: 60, kind: "actor", label: "Usuario vincula credencial", sub: ["CUIL + password PJN"] },
		{
			id: "proc",
			x: 40,
			y: 180,
			w: 210,
			h: 84,
			kind: "private",
			label: "credentials-processor",
			sub: ["pjn-mis-causas (worker_02)", "lista portal 'Mis Causas'", "todas las causas del abogado"],
		},
		{ id: "decide", x: 350, y: 192, w: 200, h: 60, kind: "db", label: "Por cada causa", sub: ["¿existe? ¿está en caché?"] },
		{
			id: "exist",
			x: 650,
			y: 28,
			w: 250,
			h: 96,
			kind: "ok",
			label: "Ya existe en causas-*",
			sub: ["push linkedCredentials", "hasActiveCredential: true", "si estaba isValid:false →", "PROMOCIÓN a válida-privada"],
		},
		{
			id: "cachePub",
			x: 650,
			y: 160,
			w: 250,
			h: 72,
			kind: "ok",
			label: "Caché: pública",
			sub: ["crea copia · source 'cache'", "isValid:true · update:true"],
		},
		{
			id: "cachePriv",
			x: 650,
			y: 270,
			w: 250,
			h: 96,
			kind: "bad",
			label: "Caché: privada ⚠",
			sub: [
				"crea verified:true · isValid:FALSE",
				"isPrivate:true · update:false",
				"nace 'inválida' y hoy nunca",
				"se promueve (bug conocido)",
			],
		},
		{
			id: "noCache",
			x: 650,
			y: 410,
			w: 250,
			h: 84,
			kind: "warn",
			label: "Sin caché",
			sub: ["crea source 'pjn-login'", "isValid:true · isPrivate:null", "(se clasifica en los updates)"],
		},
		{
			id: "folder",
			x: 350,
			y: 410,
			w: 200,
			h: 96,
			kind: "db",
			label: "ensureFolder",
			sub: ["crea un folder por causa", "archived:true si excede", "el límite del plan"],
		},
	],
	edges: [
		{ id: "c1", from: "user", to: "proc" },
		{ id: "c2", from: "proc", to: "decide" },
		{ id: "c3", from: "decide", to: "exist", kind: "ok", label: "existe (local_db)" },
		{ id: "c4", from: "decide", to: "cachePub", kind: "ok", label: "caché isValid:true" },
		{ id: "c5", from: "decide", to: "cachePriv", kind: "problem", label: "caché isValid:false" },
		{ id: "c6", from: "decide", to: "noCache", label: "no está en caché" },
		{ id: "c7", from: "proc", to: "folder", label: "crea folders", fromSide: "bottom", toSide: "left" },
	],
	steps: [
		{ title: "Vista completa", text: "Las 4 ramas del sync inicial por credencial, y la creación de folders con límite de plan." },
		{
			title: "El listado autenticado",
			text: "credentials-processor entra al portal Mis Causas con la credencial del usuario (SSO, sin captcha). Ese listado es la fuente de verdad de qué causas tiene el abogado, incluidas las reservadas que la consulta pública jamás mostraría.",
			nodes: ["user", "proc", "decide"],
			edges: ["c1", "c2"],
		},
		{
			title: "Existente: la única promoción que hay hoy",
			text: "Si la causa ya estaba en la base (la creó otro flujo), se vincula la credencial. Y acá vive la ÚNICA promoción del sistema: si estaba isValid:false (el verify público había fallado), encontrarla en el listado autenticado es prueba positiva de existencia → flip a isValid:true + isPrivate:true (causa-sync-service.js:1006). Este mecanismo NO corre para las demás ramas ni en los updates posteriores.",
			nodes: ["proc", "decide", "exist"],
			edges: ["c2", "c3"],
		},
		{
			title: "Caché pública",
			text: "El caché la conoce y es pública: se crea la copia completa con isValid:true y update:true. Queda apta para el ciclo público si algún día pierde la credencial.",
			nodes: ["proc", "decide", "cachePub"],
			edges: ["c2", "c4"],
		},
		{
			title: "Caché privada: nace 'inválida' ⚠",
			text: "El caché marca isValid:false = privada. La causa se crea con datos reales (carátula, juzgado) pero verified:true + isValid:FALSE + update:false (causa-sync-service.js:394). Como private-causas-update-worker nunca toca isValid, queda 'inválida' para siempre aunque se sincronice todos los días. Este es el origen del grueso de la vista admin 'Carpetas No Verificadas'.",
			nodes: ["proc", "decide", "cachePriv"],
			edges: ["c2", "c5"],
		},
		{
			title: "Sin caché: isPrivate pendiente",
			text: "Se crea con source:'pjn-login', isValid:true e isPrivate:null. El private-causas-update-worker la clasificará en los próximos updates: si la búsqueda pública la encuentra → isPrivate:false; si solo aparece en Mis Causas → isPrivate:true.",
			nodes: ["proc", "decide", "noCache"],
			edges: ["c2", "c6"],
		},
		{
			title: "Folders y límite de plan",
			text: "ensureFolder crea un folder por causa sincronizada. Si el usuario excede el cupo de folders activos de su plan, los excedentes se crean con archived:true — no aparecen en su lista activa hasta que los desarchive o mejore el plan. (Por eso muchos folders de causas privadas figuran archivados: es el límite del plan, no un error.)",
			nodes: ["proc", "folder"],
			edges: ["c7"],
		},
	],
};

// ============================================================================
// 4. VIDA PÚBLICA (pjn-workers)
// ============================================================================
export const vidaPublicaSpec: FlowSpec = {
	id: "vida-publica",
	title: "Ciclo público",
	intro:
		"El mundo de pjn-workers: verificación con captcha, ciclo diario de updates, reintentos de atoradas y detección de privacidad. Acá viven los dos 'flips' que mandan causas con datos a la vista de No Verificadas.",
	width: 1120,
	height: 540,
	nodes: [
		{ id: "pend", x: 40, y: 40, w: 210, h: 60, kind: "db", label: "Pendientes", sub: ["verified:false (source 'app')"] },
		{ id: "verify", x: 40, y: 180, w: 210, h: 72, kind: "public", label: "verify-worker", sub: ["consulta pública", "resuelve captcha"] },
		{
			id: "ok",
			x: 350,
			y: 28,
			w: 250,
			h: 84,
			kind: "ok",
			label: "Válida",
			sub: ["isValid:true · update:true", "carátula + movimientos", "folders → success"],
		},
		{
			id: "inex",
			x: 350,
			y: 150,
			w: 250,
			h: 84,
			kind: "bad",
			label: "Inexistente / no pública",
			sub: ["isValid:false · carátula 'N/A'", "folders → failed (gate UI)", "las privadas caen SIEMPRE acá"],
		},
		{
			id: "err",
			x: 350,
			y: 280,
			w: 250,
			h: 96,
			kind: "bad",
			label: "Error genérico ⚠",
			sub: ["isValid:false SIN borrar datos", "update:false", "un error transitorio también", "flipea causas sanas"],
		},
		{
			id: "upd",
			x: 700,
			y: 28,
			w: 240,
			h: 96,
			kind: "public",
			label: "app-update-worker",
			sub: ["toma isValid:true + update:true", "+ SIN credencial activa", "movimientos nuevos diarios"],
		},
		{
			id: "stuck",
			x: 700,
			y: 180,
			w: 240,
			h: 84,
			kind: "public",
			label: "stuck-documents-worker",
			sub: ["reintenta atoradas", "también puede flipear", "isValid:false"],
		},
		{
			id: "privacy",
			x: 700,
			y: 330,
			w: 240,
			h: 96,
			kind: "public",
			label: "pjn-privacy-checker",
			sub: ["accessFailureCount ≥ umbral", "→ isPrivate:true", "+ folder.causaIsPrivate", "+ email al usuario"],
		},
		{
			id: "foldersN",
			x: 350,
			y: 430,
			w: 250,
			h: 72,
			kind: "db",
			label: "Folders",
			sub: ["'failed' → el gate bloquea el", "detalle en la UI del usuario"],
		},
	],
	edges: [
		{ id: "v1", from: "pend", to: "verify" },
		{ id: "v2", from: "verify", to: "ok", kind: "ok", label: "existe y es pública" },
		{ id: "v3", from: "verify", to: "inex", kind: "problem", label: "PJN la rechaza" },
		{ id: "v4", from: "verify", to: "err", kind: "problem", label: "error de scraping" },
		{ id: "v5", from: "ok", to: "upd", label: "ciclo diario" },
		{ id: "v6", from: "upd", to: "stuck", label: "atoradas" },
		{ id: "v7", from: "stuck", to: "err", kind: "problem", label: "flip", fromSide: "bottom", toSide: "right" },
		{ id: "v8", from: "upd", to: "privacy", label: "fallos repetidos", fromSide: "right", toSide: "right", labelDx: 30 },
		{
			id: "v9",
			from: "inex",
			to: "foldersN",
			kind: "problem",
			fromSide: "left",
			toSide: "left",
			label: "updateFoldersOnError",
			labelDx: -30,
		},
		{ id: "v10", from: "err", to: "foldersN", kind: "problem" },
	],
	steps: [
		{
			title: "Vista completa",
			text: "Verificación, ciclo de updates y los caminos que terminan marcando causas y folders como inválidos.",
		},
		{
			title: "Verificación: 3 salidas",
			text: "verify-worker consulta el PJN público. Salidas: (1) válida → datos + movimientos, entra al ciclo; (2) 'Expediente inexistente o no disponible para su consulta pública' → isValid:false — nota: las causas PRIVADAS caen siempre acá aunque existan; (3) error de scraping genérico → también isValid:false, sin borrar los datos que ya tenía (verify-document.js:552).",
			nodes: ["pend", "verify", "ok", "inex", "err"],
			edges: ["v1", "v2", "v3", "v4"],
		},
		{
			title: "Ciclo diario de updates",
			text: "app-update-worker toma las causas isValid:true + update:true y les trae movimientos nuevos. Excluye las que tienen hasActiveCredential:true — esas pertenecen al mundo privado. Es la razón por la que vincular una credencial 'muda' la causa de mundo.",
			nodes: ["ok", "upd"],
			edges: ["v5"],
		},
		{
			title: "Atoradas y su flip",
			text: "stuck-documents-worker reintenta causas con scraping incompleto. Si verifyDocument devuelve isValid:false (incluida una privada que la consulta pública rechaza), persiste isValid:false + scrapingProgress:'invalid' sin borrar datos (stuck-documents-worker.js:576). Así una causa con 200+ movimientos puede aterrizar en 'No Verificadas'.",
			nodes: ["upd", "stuck", "err"],
			edges: ["v6", "v7"],
		},
		{
			title: "Detección de privacidad",
			text: "Cuando una causa acumula fallos de acceso repetidos (accessFailureCount ≥ umbral), pjn-privacy-checker la marca isPrivate:true, setea causaIsPrivate en el folder y avisa por email. Es la señal de 'se volvió privada' — pero hoy NO revierte el isValid:false ni la entrega al mundo privado si no hay credencial.",
			nodes: ["upd", "privacy"],
			edges: ["v8"],
		},
		{
			title: "Propagación a folders",
			text: "Los flips inválidos propagan a los folders: causaAssociationStatus:'failed' + causaIsValid:false (updateFoldersOnError). El verificationGate del front entonces bloquea el detalle completo del folder — el usuario solo ve 'reintentar / soporte / eliminar'.",
			nodes: ["inex", "err", "foldersN"],
			edges: ["v9", "v10"],
		},
	],
};

// ============================================================================
// 5. VIDA PRIVADA (pjn-mis-causas)
// ============================================================================
export const vidaPrivadaSpec: FlowSpec = {
	id: "vida-privada",
	title: "Ciclo privado",
	intro:
		"private-causas-update-worker: el worker que requiere credenciales. Selecciona TODAS las causas con credencial vinculada (sin filtrar isValid) y decide el método de scraping según isPrivate. Nunca promueve isValid — ese es el hueco central.",
	width: 1120,
	height: 540,
	nodes: [
		{
			id: "sel",
			x: 40,
			y: 40,
			w: 240,
			h: 96,
			kind: "private",
			label: "Selección de causas",
			sub: ["linkedCredentials no vacío", "SIN filtro isValid ni update", "source: pjn-login / cache / app", "oldest-first por lastUpdate"],
		},
		{
			id: "creds",
			x: 40,
			y: 210,
			w: 240,
			h: 72,
			kind: "private",
			label: "getActiveCredentials",
			sub: ["solo credenciales enabled", "agrupa causas por credencial"],
		},
		{
			id: "pTrue",
			x: 380,
			y: 28,
			w: 250,
			h: 72,
			kind: "private",
			label: "isPrivate: true",
			sub: ["directo al portal Mis Causas", "(la búsqueda pública siempre falla)"],
		},
		{ id: "pFalse", x: 380, y: 140, w: 250, h: 60, kind: "private", label: "isPrivate: false", sub: ["búsqueda pública por número"] },
		{
			id: "pNull",
			x: 380,
			y: 250,
			w: 250,
			h: 84,
			kind: "private",
			label: "isPrivate: null",
			sub: ["búsqueda pública primero", "fallback: listado Mis Causas", "→ clasifica isPrivate true/false"],
		},
		{
			id: "updOk",
			x: 740,
			y: 130,
			w: 250,
			h: 96,
			kind: "ok",
			label: "Actualiza la causa",
			sub: ["movimientos + metadata", "actualiza folders del usuario", "⚠ NUNCA promueve isValid", "(el falso inválido persiste)"],
		},
		{
			id: "orphan",
			x: 380,
			y: 400,
			w: 250,
			h: 96,
			kind: "bad",
			label: "Credencial muere ⚠",
			sub: [
				"disabled → sale del privado",
				"si además isValid:false / update:false",
				"el público tampoco la toma",
				"→ congelada en silencio",
			],
		},
	],
	edges: [
		{ id: "p1", from: "sel", to: "creds" },
		{ id: "p2a", from: "creds", to: "pTrue", label: "por causa" },
		{ id: "p2b", from: "creds", to: "pFalse" },
		{ id: "p2c", from: "creds", to: "pNull" },
		{ id: "p3a", from: "pTrue", to: "updOk", kind: "ok" },
		{ id: "p3b", from: "pFalse", to: "updOk", kind: "ok" },
		{ id: "p3c", from: "pNull", to: "updOk", kind: "ok" },
		{ id: "p4", from: "creds", to: "orphan", kind: "problem", label: "credencial disabled", fromSide: "bottom", toSide: "left" },
	],
	steps: [
		{
			title: "Vista completa",
			text: "Selección, clasificación por isPrivate y el destino de las causas cuando la credencial deja de estar activa.",
		},
		{
			title: "Selección sin filtro isValid",
			text: "La query toma toda causa con linkedCredentials, sin mirar isValid ni update (private-causas-update-worker.js:620). Por eso las privadas que figuran 'inválidas' en el admin SÍ se siguen actualizando a diario — el problema es de flags, no de scraping… siempre que la credencial siga viva.",
			nodes: ["sel", "creds"],
			edges: ["p1"],
		},
		{
			title: "El ternario isPrivate",
			text: "isPrivate:true va directo al portal autenticado (la pública siempre la rechaza, no tiene sentido intentar). isPrivate:false usa la búsqueda pública. isPrivate:null es la indeterminada: prueba pública primero y si no aparece la busca en el listado de Mis Causas — y con eso la clasifica definitivamente.",
			nodes: ["creds", "pTrue", "pFalse", "pNull"],
			edges: ["p2a", "p2b", "p2c"],
		},
		{
			title: "Update sin promoción ⚠",
			text: "El update trae movimientos y metadata y actualiza los folders, pero jamás escribe isValid. Una causa que nació isValid:false desde el caché privado se sincroniza perfecta todos los días y sigue figurando 'inválida' en la vista admin. La promoción existe solo en el sync inicial (rama local_db) — falta replicarla acá.",
			nodes: ["pTrue", "pFalse", "pNull", "updOk"],
			edges: ["p3a", "p3b", "p3c"],
		},
		{
			title: "Huérfanas",
			text: "Si la credencial se deshabilita, getActiveCredentials la filtra y sus causas salen del mundo privado. Las que además tienen isValid:false / update:false tampoco califican para el público → quedan congeladas sin que nadie lo note. Hoy hay ~15 causas en este estado (varias desde julio).",
			nodes: ["creds", "orphan"],
			edges: ["p4"],
		},
	],
};

// ============================================================================
// 6. ESCENARIOS DUALES — un spec por escenario
// ============================================================================
export const escenarioS1: FlowSpec = {
	id: "esc-s1",
	title: "S1 · Nace pública → llega la credencial",
	intro: "El caso feliz del diseño dual: la causa cambia de mundo sin fricción cuando el usuario vincula su credencial.",
	width: 1120,
	height: 400,
	nodes: [
		{
			id: "born",
			x: 40,
			y: 40,
			w: 240,
			h: 84,
			kind: "ok",
			label: "Causa nace pública",
			sub: ["alta app o scraping", "verify → isValid:true", "update público diario"],
		},
		{ id: "pub", x: 40, y: 240, w: 240, h: 60, kind: "public", label: "pjn-workers la trabaja", sub: ["captcha, consulta pública"] },
		{
			id: "link",
			x: 400,
			y: 40,
			w: 250,
			h: 72,
			kind: "actor",
			label: "Usuario vincula credencial",
			sub: ["el sync la encuentra en el", "listado de Mis Causas"],
		},
		{
			id: "prom",
			x: 400,
			y: 200,
			w: 250,
			h: 96,
			kind: "ok",
			label: "Vinculación (local_db)",
			sub: ["push linkedCredentials", "hasActiveCredential: true", "si estaba inválida →", "promoción isValid:true"],
		},
		{
			id: "priv",
			x: 760,
			y: 200,
			w: 250,
			h: 84,
			kind: "private",
			label: "El privado toma el update",
			sub: ["el público la excluye por", "hasActiveCredential", "login sin captcha"],
		},
	],
	edges: [
		{ id: "s1a", from: "born", to: "pub", label: "ciclo diario" },
		{ id: "s1b", from: "link", to: "prom" },
		{ id: "s1c", from: "born", to: "prom", kind: "handoff", label: "misma causa, doc único" },
		{ id: "s1d", from: "prom", to: "priv", kind: "handoff", label: "handoff de mundo" },
	],
	steps: [
		{ title: "Vista completa", text: "El único handoff bien resuelto hoy: público → privado vía vinculación de credencial." },
		{
			title: "1 · Vida pública",
			text: "La causa existe con isValid:true y el app-update-worker la refresca a diario resolviendo captchas.",
			nodes: ["born", "pub"],
			edges: ["s1a"],
		},
		{
			title: "2 · Llega la credencial",
			text: "El sync inicial encuentra la causa ya creada (rama local_db): agrega la credencial a linkedCredentials y marca hasActiveCredential:true. Si el público la había flipeado a inválida, acá se promueve de vuelta a isValid:true + isPrivate:true.",
			nodes: ["link", "prom", "born"],
			edges: ["s1b", "s1c"],
		},
		{
			title: "3 · Cambio de mundo",
			text: "Desde entonces el público la excluye (hasActiveCredential) y private-causas-update-worker la actualiza vía login, sin captcha. Los folders de TODOS los usuarios que comparten la causa se benefician.",
			nodes: ["prom", "priv"],
			edges: ["s1d"],
		},
	],
};

export const escenarioS2: FlowSpec = {
	id: "esc-s2",
	title: "S2 · Nace privada desde el caché",
	intro:
		"El origen del grueso de la vista 'Carpetas No Verificadas': causas reales, sincronizadas a diario, que figuran inválidas de nacimiento.",
	width: 1120,
	height: 400,
	nodes: [
		{
			id: "sync",
			x: 40,
			y: 40,
			w: 240,
			h: 72,
			kind: "private",
			label: "credentials-processor",
			sub: ["sync inicial de la credencial", "el caché la marca privada"],
		},
		{
			id: "birth",
			x: 400,
			y: 28,
			w: 260,
			h: 96,
			kind: "bad",
			label: "Nace 'inválida' ⚠",
			sub: ["verified:true · isValid:FALSE", "isPrivate:true · update:false", "con carátula y datos reales", "(causa-sync-service.js:394)"],
		},
		{
			id: "daily",
			x: 400,
			y: 250,
			w: 260,
			h: 84,
			kind: "private",
			label: "Update privado diario",
			sub: ["movimientos al día", "folders actualizados", "pero isValid no se toca"],
		},
		{
			id: "admin",
			x: 760,
			y: 28,
			w: 250,
			h: 84,
			kind: "warn",
			label: "Admin: 'No Verificadas'",
			sub: ["falso inválido visible", "con datos completos", "(lo que motivó esta página)"],
		},
		{
			id: "folderOk",
			x: 760,
			y: 250,
			w: 250,
			h: 84,
			kind: "db",
			label: "Folder del usuario",
			sub: ["flags en success (no bloqueado)", "muchos nacen archived", "por límite de plan"],
		},
	],
	edges: [
		{ id: "s2a", from: "sync", to: "birth", kind: "problem", label: "caché isValid:false" },
		{ id: "s2b", from: "birth", to: "daily", label: "linkedCredentials" },
		{ id: "s2c", from: "birth", to: "admin", kind: "problem", label: "queda expuesta" },
		{ id: "s2d", from: "daily", to: "folderOk", kind: "ok" },
	],
	steps: [
		{ title: "Vista completa", text: "Una causa sana operativamente, rota en sus flags." },
		{
			title: "1 · Nacimiento marcado",
			text: "El caché conoce la causa como privada (isValid:false en el caché significa 'no consultable públicamente'). Al crearla, el sync copia ese estado: la causa nace verified:true + isValid:false + isPrivate:true, con sus datos reales.",
			nodes: ["sync", "birth"],
			edges: ["s2a"],
		},
		{
			title: "2 · Vida normal… con flag roto",
			text: "El worker privado la actualiza a diario (su selección no filtra isValid) y los folders reciben movimientos. Operativamente está viva. Pero como nada promueve isValid, en el admin aparece eternamente como 'no verificada' — 41 de las 46 actuales son exactamente este caso.",
			nodes: ["birth", "daily", "admin", "folderOk"],
			edges: ["s2b", "s2c", "s2d"],
		},
	],
};

export const escenarioS3: FlowSpec = {
	id: "esc-s3",
	title: "S3 · Pública se vuelve privada",
	intro:
		"El PJN restringe una causa que era pública. El resultado depende de si algún usuario tiene credencial vinculada — y hoy en ambos casos quedan flags rotos.",
	width: 1120,
	height: 480,
	nodes: [
		{
			id: "pubOk",
			x: 40,
			y: 40,
			w: 230,
			h: 72,
			kind: "ok",
			label: "Causa pública sana",
			sub: ["isValid:true · update:true", "ciclo público diario"],
		},
		{
			id: "flip",
			x: 370,
			y: 28,
			w: 260,
			h: 96,
			kind: "bad",
			label: "PJN la restringe",
			sub: ["update/stuck fallan →", "flip isValid:false · update:false", "los datos quedan intactos", "privacy-checker → isPrivate:true"],
		},
		{
			id: "foldersFail",
			x: 370,
			y: 360,
			w: 260,
			h: 84,
			kind: "bad",
			label: "Folders → 'failed'",
			sub: ["updateFoldersOnError", "el gate bloquea el detalle", "en la UI del usuario"],
		},
		{
			id: "withCred",
			x: 740,
			y: 28,
			w: 260,
			h: 96,
			kind: "private",
			label: "Con credencial vinculada",
			sub: ["el privado la sigue actualizando", "(no filtra isValid)", "pero isValid/folders quedan", "rotos hasta intervención"],
		},
		{
			id: "noCred",
			x: 740,
			y: 200,
			w: 260,
			h: 96,
			kind: "bad",
			label: "Sin credencial ⚠",
			sub: ["nadie puede scrapearla", "(la pública la rechaza)", "→ huérfana congelada", "rescate: vincular credencial"],
		},
	],
	edges: [
		{ id: "s3a", from: "pubOk", to: "flip", kind: "problem", label: "restricción" },
		{ id: "s3b", from: "flip", to: "foldersFail", kind: "problem", label: "propaga" },
		{ id: "s3c", from: "flip", to: "withCred", kind: "handoff", label: "¿hay credencial? sí" },
		{ id: "s3d", from: "flip", to: "noCred", kind: "problem", label: "no", fromSide: "bottom", toSide: "left" },
	],
	steps: [
		{ title: "Vista completa", text: "La transición pública → privada y sus dos destinos." },
		{
			title: "1 · El flip",
			text: "La consulta pública empieza a responder 'no disponible'. update/stuck marcan isValid:false + update:false sin borrar datos, y tras varios fallos privacy-checker la clasifica isPrivate:true y avisa al usuario por email.",
			nodes: ["pubOk", "flip"],
			edges: ["s3a"],
		},
		{
			title: "2 · Impacto en el usuario",
			text: "Los folders pasan a causaAssociationStatus:'failed' → el verificationGate reemplaza el detalle del folder por PendingVerificationView. El usuario pierde acceso a movimientos que la base todavía tiene.",
			nodes: ["flip", "foldersFail"],
			edges: ["s3b"],
		},
		{
			title: "3 · Con credencial: sigue viva, flags rotos",
			text: "Si algún usuario de la causa tiene credencial, el privado la sigue sincronizando (su query no filtra isValid). Pero nada revierte el isValid:false ni el 'failed' de los folders — el fix propuesto es que el update privado exitoso promueva ambos.",
			nodes: ["flip", "withCred"],
			edges: ["s3c"],
		},
		{
			title: "4 · Sin credencial: huérfana",
			text: "Sin credencial no existe forma de scrapearla: la pública la rechaza y el privado no la selecciona. Queda congelada en silencio. La única vía de rescate es que un usuario vincule su credencial PJN (el sync la promovería vía la rama local_db).",
			nodes: ["flip", "noCred"],
			edges: ["s3d"],
		},
	],
};

export const escenarioS4: FlowSpec = {
	id: "esc-s4",
	title: "S4 · La credencial muere",
	intro: "El espejo de S1: la causa pierde su vía de scraping privada y, si sus flags dicen 'inválida', ningún mundo la recupera.",
	width: 1120,
	height: 380,
	nodes: [
		{
			id: "priv",
			x: 40,
			y: 40,
			w: 250,
			h: 84,
			kind: "private",
			label: "Privada con credencial",
			sub: ["isPrivate:true · isValid:false", "(nació del caché privado)", "update privado diario, sana"],
		},
		{
			id: "dead",
			x: 400,
			y: 40,
			w: 250,
			h: 84,
			kind: "bad",
			label: "Credencial disabled",
			sub: ["password vencida, baja, etc.", "getActiveCredentials la filtra", "sus causas salen del privado"],
		},
		{
			id: "frozen",
			x: 760,
			y: 40,
			w: 250,
			h: 96,
			kind: "bad",
			label: "Congelada ⚠",
			sub: ["el público la ignora:", "isValid:false · update:false", "hasActiveCredential desactualizado", "nadie la vuelve a tocar"],
		},
		{
			id: "fix",
			x: 400,
			y: 240,
			w: 250,
			h: 84,
			kind: "warn",
			label: "Rescate",
			sub: ["usuario reconecta credencial", "o intervención admin", "(hoy no hay alerta automática)"],
		},
	],
	edges: [
		{ id: "s4a", from: "priv", to: "dead", kind: "problem", label: "credencial cae" },
		{ id: "s4b", from: "dead", to: "frozen", kind: "problem" },
		{ id: "s4c", from: "dead", to: "fix", kind: "handoff", label: "única salida" },
	],
	steps: [
		{ title: "Vista completa", text: "Cómo una causa operativa queda sin ningún worker que la atienda." },
		{
			title: "1 · La credencial cae",
			text: "PjnCredentials pasa a enabled:false (password vencida, usuario dado de baja). getActiveCredentials filtra solo credenciales enabled, así que las causas de esa credencial dejan de entrar a las corridas del worker privado.",
			nodes: ["priv", "dead"],
			edges: ["s4a"],
		},
		{
			title: "2 · Ningún mundo la toma",
			text: "El público exige isValid:true + update:true — esta causa tiene ambos en false por su nacimiento privado. Resultado: congelada en silencio, sin updates ni alertas. En Atlas hay ~15 causas así, varias sin tocar desde julio (una con folder activo de usuario).",
			nodes: ["dead", "frozen"],
			edges: ["s4b"],
		},
		{
			title: "3 · Rescate",
			text: "Hoy la única salida es manual: que el usuario reconecte su credencial (el sync re-vincula) o intervención desde el admin. Mejora pendiente: detectar huérfanas y notificar al usuario que su credencial necesita reconexión.",
			nodes: ["dead", "fix"],
			edges: ["s4c"],
		},
	],
};

export const escenarios: FlowSpec[] = [escenarioS1, escenarioS2, escenarioS3, escenarioS4];

export const mainSpecs: FlowSpec[] = [generalSpec, altaAppSpec, altaCredSpec, vidaPublicaSpec, vidaPrivadaSpec];
